version: '2'
services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: userDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always